version: '3'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

